### ISSUE TITLE
Remove IP-based location determination?

### ISSUE THREAD

**Issue by slager** [ropensci/rebird#115]
I'm wondering if we should just remove the IP-based location determination. It's neat, but it creates potential privacy issues by exposing IP address and coordinates in the VCR fixtures. Also my experimenting with it shows that the location can be quite far off from my actual location.

**Comment by jrdnbradford** [comment]
It looks like you can filter data via regex in {`vcr`}, so something like this would remove coordinates from URLs and JSON strings in the fixtures:

```diff
library("vcr") # *Required* as vcr is set up on loading
invisible(vcr::vcr_configure(
  filter_sensitive_data = list("<<<redacted>>>" = Sys.getenv('EBIRD_KEY')),
+ filter_sensitive_data_regex = list(
+   '"lat":<<<redacted>>>' = '("lat"|"latitude"):(-?\\d+(\\.\\d+)?)',
+   "lat=<<<redacted>>>" = '(lat|latitude)=(-?\\d+(\\.\\d+)?)',
+   '"lng":<<<redacted>>>' = '("lng"|:"longitude"):(-?\\d+(\\.\\d+)?)',
+   "lng=<<<redacted>>>" = '(lng|longitude)=(-?\\d+(\\.\\d+)?)'
+ ),
  dir = vcr::vcr_test_path("fixtures")
))
```
If redaction is the route you want to go I'm happy to take a look.

**Comment by slager** [comment]
I tried at one point using vcr/regex to redact latitude, longitude, and IP address, but iirc the tricky part is that they occur inside a long string value.  If you can get it to work, go for it.

**Comment by jrdnbradford** [comment]
I tried a few things but every solution I tried that redacted the relevant data ended up causing issues with the vcr testing setup. 🫠

**Comment by sckott** [comment]
👋🏽 hi, vcr maintainer here.  Is there a small reproducible example I can play with to understand the problem and see what the best solution is?

**Comment by RichardLitt** [comment]
I am not an expert here. 

Running `testthat::test_file("tests/testthat/test-ebirdgeo.R", reporter="summary")`, I expected vcr to make a fixture in the line where I wrote `expect_no_error`. It didn't and I'm not sure why. But this should call `getlatlng`, which should look for my IP address and use that to get a location - which is what we're trying to avoid putting into the fixtures. 

```
vcr::use_cassette("ebirdgeo", {
  test_that("ebirdgeo works correctly", {
    expect_warning(egeo <- ebirdgeo('amegfi', 42.45, -76.50, dist = 51, max = 2),
                   "Distance supplied was >50km")
    # Added this line
    expect_no_error(ebirdgeo('amegfi'))
    expect_true(inherits(egeo, "data.frame"))
    expect_gt(NCOL(egeo), 10)
    expect_equal(nrow(egeo), 2)
    expect_true(inherits(egeo$locName, "character"))
    expect_true(inherits(egeo$howMany, "integer"))
    expect_warning(
      prov <- ebirdgeo(
        lat = 42.45, lng = -76.50, max=2,
        provisional=TRUE, hotspot=TRUE, back = 31.5),
      "using 30 days"
    )
    expect_true(inherits(prov, "data.frame"))
  })
})
```

**Comment by slager** [comment]
For a reprex of the main problem here as I understand it, clone the `vcr_demo` branch of this repo and run `devtools::test(filter = 'DEMO')` to create the DEMO.yml fixture.  The goal is for `string` in this fixture to have the IP address redacted.

**Comment by RichardLitt** [comment]
Running this: 

```R
  filter_sensitive_data_regex = list(": \"<<<redacted>>>\"," = ': ".*",'),
```

I managed to get this:

```yml
http_interactions:
- request:
    method: get
    uri: http://ipinfo.io/
    body:
      encoding: ''
      string: ''
    headers:
      Accept: application/json, text/xml, application/xml, */*
  response:
    status:
      status_code: 200
      category: Success
      reason: OK
      message: 'Success: (200) OK'
    headers:
      access-control-allow-origin: '*'
      content-encoding: gzip
      content-type: application/json; charset=utf-8
      date: Thu, 03 Oct 2024 08:50:13 GMT
      referrer-policy: strict-origin-when-cross-origin
      vary: Accept-Encoding
      x-content-type-options: nosniff
      x-frame-options: SAMEORIGIN
      x-xss-protection: 1; mode=block
      content-length: '236'
      via: 1.1 google
      strict-transport-security: max-age=2592000; includeSubDomains
    body:
      encoding: ''
      file: no
      string: |-
        {
          "ip": "<<<redacted>>>",
          "readme": "https://ipinfo.io/missingauth"
        }
  recorded_at: 2024-10-03 08:50:13 GMT
  recorded_with: vcr/1.6.0, webmockr/0.9.0
  ```
  
  I think this is what we want.
